<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getConfiguration</value>
  <value name="encodeutf8">true</value>
  <value name="body">IA0KDQovLyBwaXBlbGluZQ0KSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5n
ZXRDdXJzb3IoKTsJCQ0KDQpQcm9wZXJ0aWVzIHByb3BzID0gZ2V0UHJvcGVydGllcygiV2ViQVBJ
Q29ubmVjdGlvbi5wcm9wZXJ0aWVzIik7DQoNClN0cmluZyBrcnlvbldlYkFQSVVSTCA9IHByb3Bz
LmdldFByb3BlcnR5KCJLcnlvbldlYkFQSVVSTCIsICJodHRwOi8vbG9jYWxob3N0OjgwODAvIik7
CQkNClN0cmluZyB1c2VyTmFtZSA9IHByb3BzLmdldFByb3BlcnR5KCJ1c2VyTmFtZSIsICJXZWJB
UElVc2VyIik7DQpTdHJpbmcgcGFzc3dvcmQgPSBnZXRQYXNzd29yZEZyb21PUE0oKTsNCg0KLy8g
Q29uZmlndXJhdGlvbg0KSURhdGEJQ29uZmlndXJhdGlvbiA9IElEYXRhRmFjdG9yeS5jcmVhdGUo
KTsNCklEYXRhQ3Vyc29yIENvbmZpZ3VyYXRpb25DdXJzb3IgPSBDb25maWd1cmF0aW9uLmdldEN1
cnNvcigpOw0KSURhdGFVdGlsLnB1dCggQ29uZmlndXJhdGlvbkN1cnNvciwgIktyeW9uV2ViQVBJ
VVJMIiwga3J5b25XZWJBUElVUkwgKTsNCklEYXRhVXRpbC5wdXQoIENvbmZpZ3VyYXRpb25DdXJz
b3IsICJVc2VyTmFtZSIsIHVzZXJOYW1lKTsNCklEYXRhVXRpbC5wdXQoIENvbmZpZ3VyYXRpb25D
dXJzb3IsICJQYXNzd29yZCIsIHBhc3N3b3JkKTsNCkNvbmZpZ3VyYXRpb25DdXJzb3IuZGVzdHJv
eSgpOw0KSURhdGFVdGlsLnB1dCggcGlwZWxpbmVDdXJzb3IsICJDb25maWd1cmF0aW9uIiwgQ29u
ZmlndXJhdGlvbiApOw0KcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOw0KDQoNCgkJ</value>
</Values>
